SELECT CONTEST_ID,
ROUND(COUNT(USER_ID) * 100/(SELECT COUNT(USER_ID) FROM USERS),2) AS PERCENTAGE
FROM REGISTER
GROUP BY CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC;

-- # GROUP THE TABLE ON THE BASIS OF CONTEST ID TO GET ALL THE 
-- # CONTEST_ID AND RESPECTIVE COUNT OF USERS 
-- AND NOW CALCULATE THE PERCENTAGE