SELECT PROJECT.PROJECT_ID AS PROJECT_ID, 
ROUND(AVG(EMPLOYEE.EXPERIENCE_YEARS),2) AS AVERAGE_YEARS 
FROM PROJECT INNER JOIN EMPLOYEE
ON PROJECT.EMPLOYEE_ID= EMPLOYEE.EMPLOYEE_ID
GROUP BY PROJECT.PROJECT_ID;